// requant_rom_x4 -- bias+k ROM, 4 independent read ports, case style, via
// emit_case_nport_grouped. GENERATED by w1_rom_synthesis/rom_gen.py --gen-ckpt-roms --
// do not edit by hand.
//
// Same 32-word bias+k content and per-word layout as requant_rom.v (see that
// file's header for the exact bit layout and the sign-field note -- this file
// stores no sign bit either, for the identical reason).
//
// Bus convention (packed, matches l2_mac_x4.v's unit-major packing): unit i's
// address is at addr[CKPT_ADDR_W*i +: CKPT_ADDR_W] and unit i's word is at
// wcol[THETAK_ROW_W*i +: THETAK_ROW_W], for i = 0..3.
//
// NARROWED CONTRACT (2026-07-30, GROUPED decode): identical to l2_weight_rom_x4.v's
// -- port i's address field MUST satisfy addr%4==i; see that file's header for the
// full rationale and emit_case_nport_grouped's docstring in rom_gen.py.
//
// Port widths come from ckpt_defs.vh: `P`=4, THETAK_ROW_W (=8), CKPT_ADDR_W
// (=5).
`include "ckpt_defs.vh"

// requant_rom_x4: style 1, 4x, GROUPED -- 4 independent case(addr)
// read ports, but each port's decode only looks at the top 3 b of
// its 5-b address field and ignores the low 2 b entirely. Valid ONLY
// because every caller is required to present addr % 4 == p to port p
// (see emit_case_nport_grouped's docstring in rom_gen.py and this file's own
// header). Content: same 32-word / 8 b-per-word data as the ungrouped emitter.
module requant_rom_x4(
    input  wire [(`P*`CKPT_ADDR_W)-1:0] addr,
    output reg  [(`P*`THETAK_ROW_W)-1:0] wcol
  );
  // port 0: addr[4:2] -> wcol[7:0] (addr[1:0] ignored, required == 0)
  always @(*) begin
    case (addr[4:2])
      3'd0: wcol[7:0] = 8'h46;
      3'd1: wcol[7:0] = 8'h76;
      3'd2: wcol[7:0] = 8'h4f;
      3'd3: wcol[7:0] = 8'h78;
      3'd4: wcol[7:0] = 8'h4d;
      3'd5: wcol[7:0] = 8'h4d;
      3'd6: wcol[7:0] = 8'h47;
      3'd7: wcol[7:0] = 8'h9d;
      default: wcol[7:0] = 8'b0;
    endcase
  end
  // port 1: addr[9:7] -> wcol[15:8] (addr[6:5] ignored, required == 1)
  always @(*) begin
    case (addr[9:7])
      3'd0: wcol[15:8] = 8'h7f;
      3'd1: wcol[15:8] = 8'h4c;
      3'd2: wcol[15:8] = 8'h49;
      3'd3: wcol[15:8] = 8'h48;
      3'd4: wcol[15:8] = 8'h4b;
      3'd5: wcol[15:8] = 8'h7c;
      3'd6: wcol[15:8] = 8'h45;
      3'd7: wcol[15:8] = 8'h41;
      default: wcol[15:8] = 8'b0;
    endcase
  end
  // port 2: addr[14:12] -> wcol[23:16] (addr[11:10] ignored, required == 2)
  always @(*) begin
    case (addr[14:12])
      3'd0: wcol[23:16] = 8'h4a;
      3'd1: wcol[23:16] = 8'h42;
      3'd2: wcol[23:16] = 8'h4b;
      3'd3: wcol[23:16] = 8'h4a;
      3'd4: wcol[23:16] = 8'h4a;
      3'd5: wcol[23:16] = 8'h7e;
      3'd6: wcol[23:16] = 8'h04;
      3'd7: wcol[23:16] = 8'h47;
      default: wcol[23:16] = 8'b0;
    endcase
  end
  // port 3: addr[19:17] -> wcol[31:24] (addr[16:15] ignored, required == 3)
  always @(*) begin
    case (addr[19:17])
      3'd0: wcol[31:24] = 8'h93;
      3'd1: wcol[31:24] = 8'h40;
      3'd2: wcol[31:24] = 8'h76;
      3'd3: wcol[31:24] = 8'h4a;
      3'd4: wcol[31:24] = 8'h07;
      3'd5: wcol[31:24] = 8'h7d;
      3'd6: wcol[31:24] = 8'h46;
      3'd7: wcol[31:24] = 8'h74;
      default: wcol[31:24] = 8'b0;
    endcase
  end
endmodule
