// l2_weight_rom_x4 -- W2 {p,n} ROM, 4 independent read ports, case style, via
// emit_case_nport_grouped (generalized from the winning 1-port case emitter -- no
// manual sharing between ports, so yosys/abc decide whether to share decode logic).
// GENERATED by w1_rom_synthesis/rom_gen.py --gen-ckpt-roms -- do not edit by hand.
//
// Same 32-word W2 content and per-word encoding as l2_weight_rom.v (see that file's
// header for the {p,n} bit convention, confirmed against l2_mac_x4.v).
//
// Bus convention (packed, matches l2_mac_x4.v's own unit-major packing of h_in/w_in,
// e.g. w_in's unit u occupies bits [20*u +: 20]): unit i's address is at
// addr[CKPT_ADDR_W*i +: CKPT_ADDR_W] and unit i's word is at
// wcol[W2_ROW_W*i +: W2_ROW_W], for i = 0..3. wcol can be wired directly into
// l2_mac_x4's w_in[79:0] port with no reshuffling -- w_in[20*u +: 20] == wcol[20*u +: 20].
//
// NARROWED CONTRACT (2026-07-30, GROUPED decode -- see emit_case_nport_grouped's
// docstring in rom_gen.py): port i's address field MUST satisfy addr%4==i, i.e.
// port i only ever reads hidden units i, i+4, i+8, ... -- the natural
// consequence of processing all 32 units in sequential blocks of 4 per cycle
// (same grouping convention as l1_acc_shadow's rd_grp, docs/cc_verilog_build_prompts.md
// line ~137). Port i's decode only looks at the top 3 b of its address field and
// silently ignores (and does not require) the low 2 b matching i in hardware -- but a
// caller that violates the invariant gets WRONG data, not an error. Callers needing
// fully independent per-port addressing must not use this module; the previous,
// fully-independent version (paid for with ~4x the decode logic -- see
// l2_synthesis/results.md "ROM decode replication") is emit_case_nport, unused here
// as of this narrowing.
//
// Port widths come from ckpt_defs.vh: `P`=4 (L2 units/cycle), W2_ROW_W (=20),
// CKPT_ADDR_W (=5).
`include "ckpt_defs.vh"

// l2_weight_rom_x4: style 1, 4x, GROUPED -- 4 independent case(addr)
// read ports, but each port's decode only looks at the top 3 b of
// its 5-b address field and ignores the low 2 b entirely. Valid ONLY
// because every caller is required to present addr % 4 == p to port p
// (see emit_case_nport_grouped's docstring in rom_gen.py and this file's own
// header). Content: same 32-word / 20 b-per-word data as the ungrouped emitter.
module l2_weight_rom_x4(
    input  wire [(`P*`CKPT_ADDR_W)-1:0] addr,
    output reg  [(`P*`W2_ROW_W)-1:0] wcol
  );
  // port 0: addr[4:2] -> wcol[19:0] (addr[1:0] ignored, required == 0)
  always @(*) begin
    case (addr[4:2])
      3'd0: wcol[19:0] = 20'h48818;
      3'd1: wcol[19:0] = 20'h82a5a;
      3'd2: wcol[19:0] = 20'h266a4;
      3'd3: wcol[19:0] = 20'h1206a;
      3'd4: wcol[19:0] = 20'h88660;
      3'd5: wcol[19:0] = 20'ha8098;
      3'd6: wcol[19:0] = 20'h416a8;
      3'd7: wcol[19:0] = 20'h29186;
      default: wcol[19:0] = 20'b0;
    endcase
  end
  // port 1: addr[9:7] -> wcol[39:20] (addr[6:5] ignored, required == 1)
  always @(*) begin
    case (addr[9:7])
      3'd0: wcol[39:20] = 20'h65a28;
      3'd1: wcol[39:20] = 20'ha8640;
      3'd2: wcol[39:20] = 20'h82aa9;
      3'd3: wcol[39:20] = 20'h18208;
      3'd4: wcol[39:20] = 20'h4a926;
      3'd5: wcol[39:20] = 20'h2a889;
      3'd6: wcol[39:20] = 20'ha2899;
      3'd7: wcol[39:20] = 20'h216a8;
      default: wcol[39:20] = 20'b0;
    endcase
  end
  // port 2: addr[14:12] -> wcol[59:40] (addr[11:10] ignored, required == 2)
  always @(*) begin
    case (addr[14:12])
      3'd0: wcol[59:40] = 20'ha0064;
      3'd1: wcol[59:40] = 20'h2660a;
      3'd2: wcol[59:40] = 20'h06a54;
      3'd3: wcol[59:40] = 20'ha4944;
      3'd4: wcol[59:40] = 20'h0a562;
      3'd5: wcol[59:40] = 20'h91180;
      3'd6: wcol[59:40] = 20'h08894;
      3'd7: wcol[59:40] = 20'ha5068;
      default: wcol[59:40] = 20'b0;
    endcase
  end
  // port 3: addr[19:17] -> wcol[79:60] (addr[16:15] ignored, required == 3)
  always @(*) begin
    case (addr[19:17])
      3'd0: wcol[79:60] = 20'h84296;
      3'd1: wcol[79:60] = 20'ha6585;
      3'd2: wcol[79:60] = 20'h6a442;
      3'd3: wcol[79:60] = 20'h92092;
      3'd4: wcol[79:60] = 20'h668aa;
      3'd5: wcol[79:60] = 20'h180a2;
      3'd6: wcol[79:60] = 20'h22198;
      3'd7: wcol[79:60] = 20'h198a1;
      default: wcol[79:60] = 20'b0;
    endcase
  end
endmodule
