// l2_weight_rom -- W2 {p,n} ROM, 1 read port, case style
// (w1_rom_synthesis/results.md's winner: case ties flat/annot, beats bool by 6.8%).
// GENERATED by w1_rom_synthesis/rom_gen.py --gen-ckpt-roms -- do not edit by hand.
//
// Source: ternary_tapeout/eightbit/stage3/FINAL4_s12_fold_a.npz, key W2 (10,32).
// Address = hidden unit index u (0..31). Word = W2[:,u] packed as {p,n} pairs,
// one pair per output class c (0..9): bit 2c = p (W2[c,u]==+1, contributes
// +h), bit 2c+1 = n (W2[c,u]==-1, contributes -h), neither bit = W2[c,u]==0. This is
// the SAME encoding l2_synthesis/rtl/l2_mac_x4.v's w_in port expects per unit
// (confirmed by reading l2_mac_x4.v:13-24 before generating this file) -- wcol wires
// straight into w_in with no reshuffling.
//
// Port widths come from ckpt_defs.vh: W2_ROW_W (=NCLASS*2=20) and CKPT_ADDR_W
// (=5, 2^5=32=NHID), not hardcoded literals.
`include "ckpt_defs.vh"

// l2_weight_rom: style 1 -- case(addr) with 32 constant literals
module l2_weight_rom(input wire [`CKPT_ADDR_W-1:0] addr, output reg [`W2_ROW_W-1:0] wcol);
  always @(*) begin
    case (addr)
      5'd0: wcol = 20'h48818;
      5'd1: wcol = 20'h65a28;
      5'd2: wcol = 20'ha0064;
      5'd3: wcol = 20'h84296;
      5'd4: wcol = 20'h82a5a;
      5'd5: wcol = 20'ha8640;
      5'd6: wcol = 20'h2660a;
      5'd7: wcol = 20'ha6585;
      5'd8: wcol = 20'h266a4;
      5'd9: wcol = 20'h82aa9;
      5'd10: wcol = 20'h06a54;
      5'd11: wcol = 20'h6a442;
      5'd12: wcol = 20'h1206a;
      5'd13: wcol = 20'h18208;
      5'd14: wcol = 20'ha4944;
      5'd15: wcol = 20'h92092;
      5'd16: wcol = 20'h88660;
      5'd17: wcol = 20'h4a926;
      5'd18: wcol = 20'h0a562;
      5'd19: wcol = 20'h668aa;
      5'd20: wcol = 20'ha8098;
      5'd21: wcol = 20'h2a889;
      5'd22: wcol = 20'h91180;
      5'd23: wcol = 20'h180a2;
      5'd24: wcol = 20'h416a8;
      5'd25: wcol = 20'ha2899;
      5'd26: wcol = 20'h08894;
      5'd27: wcol = 20'h22198;
      5'd28: wcol = 20'h29186;
      5'd29: wcol = 20'h216a8;
      5'd30: wcol = 20'ha5068;
      5'd31: wcol = 20'h198a1;
      default: wcol = 20'b0;
    endcase
  end
endmodule
