// requant_rom -- bias+k ROM, 1 read port, case style.
// GENERATED by w1_rom_synthesis/rom_gen.py --gen-ckpt-roms -- do not edit by hand.
//
// Source: ternary_tapeout/eightbit/stage3/FINAL4_s12_fold_a.npz, keys bias (32,)
// and k (32,). Address = hidden unit index u. Word layout, MSB to LSB:
//   word[7:6] = k[u], unsigned 2 b (ckpt_defs.vh K_W; measured k in {0,1,2})
//   word[5:0]   = bias[u], two's complement 6 b (ckpt_defs.vh CKPT_BIAS_W;
//                     measured range [-12,29], fits signed 6 b [-32,31])
// Total row width 8 b (CKPT_BIAS_W+K_W), i.e. 256 b stored for all 32
// units -- much smaller than docs/cc_32h_area_cookbook.md's cited "504 b of bias"
// figure for this ROM. 504 does not divide evenly across 32 units (504/32=15.75),
// so that number was never a per-unit bit budget; it reads as a conservative/imprecise
// placeholder, not a requirement this ROM has to match. The measured 6-bit
// two's-complement range above is the honest number for this fold.
//
// SIGN FIELD: this word format stores NO sign bit. FINAL4's sign array (npz key
// "sign") is measured +1 for all 32 units in this fold -- i.e. constant, no
// reloadable storage needed -- so it is omitted entirely rather than wired through.
// If a future checkpoint ever needs a variable sign field, it MUST be stored as the
// COMPLEMENT of the raw sign value: sgn_bit = 1 when sign==-1, sgn_bit = 0 when
// sign==+1 -- never the raw sign value. Reason: l2_synthesis/rtl/requant_unit.v's `sgn`
// port is a NEGATE flag (sgn=1 negates a1, sgn=0 passes through); wiring the raw
// sign value straight into a stored sgn bit would negate every activation whenever
// sign==+1 ("multiply by +1"), which is exactly invariant I1 in
// docs/cc_verilog_build_prompts.md §0.1 -- compiles clean, computes garbage. At the
// (out-of-scope-here) integration site where requant_unit is eventually instantiated,
// sgn should simply be tied to 0 for this fold.
//
// Port widths come from ckpt_defs.vh: THETAK_ROW_W (=CKPT_BIAS_W+K_W=8) and
// CKPT_ADDR_W (=5), not hardcoded literals.
`include "ckpt_defs.vh"

// requant_rom: style 1 -- case(addr) with 32 constant literals
module requant_rom(input wire [`CKPT_ADDR_W-1:0] addr, output reg [`THETAK_ROW_W-1:0] wcol);
  always @(*) begin
    case (addr)
      5'd0: wcol = 8'h46;
      5'd1: wcol = 8'h7f;
      5'd2: wcol = 8'h4a;
      5'd3: wcol = 8'h93;
      5'd4: wcol = 8'h76;
      5'd5: wcol = 8'h4c;
      5'd6: wcol = 8'h42;
      5'd7: wcol = 8'h40;
      5'd8: wcol = 8'h4f;
      5'd9: wcol = 8'h49;
      5'd10: wcol = 8'h4b;
      5'd11: wcol = 8'h76;
      5'd12: wcol = 8'h78;
      5'd13: wcol = 8'h48;
      5'd14: wcol = 8'h4a;
      5'd15: wcol = 8'h4a;
      5'd16: wcol = 8'h4d;
      5'd17: wcol = 8'h4b;
      5'd18: wcol = 8'h4a;
      5'd19: wcol = 8'h07;
      5'd20: wcol = 8'h4d;
      5'd21: wcol = 8'h7c;
      5'd22: wcol = 8'h7e;
      5'd23: wcol = 8'h7d;
      5'd24: wcol = 8'h47;
      5'd25: wcol = 8'h45;
      5'd26: wcol = 8'h04;
      5'd27: wcol = 8'h46;
      5'd28: wcol = 8'h9d;
      5'd29: wcol = 8'h41;
      5'd30: wcol = 8'h47;
      5'd31: wcol = 8'h74;
      default: wcol = 8'b0;
    endcase
  end
endmodule
